services:
  dedicated-server:
    image: 
    # build: # only use in test
    #   context: .
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 7778:7778/udp
      # - 8212:8212/tcp # only use in RESTAPI_ENABLED=true
      # - 25575:25575/tcp # only use in RCON_ENABLED=true
    environment:
      - GAME_PORT=7778
      - MAX_PLAYERS=32
      - ENABLE_MULTITHREAD=true
      - IS_PUBLIC=false
      - PUBLIC_IP=
      - PUBLIC_PORT=
      - FORCE_UPDATE=false
      - SERVER_NAME=Default Subistence Server
      - SERVER_DESC=Default Subistence Server
      - ADMIN_PASSWORD=changeme
      - SERVER_PASSWORD=
      - RCON_ENABLED=false
      - RCON_PORT=7779
      - RESTAPI_ENABLED=false
      - RESTAPI_PORT=7778
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/opt/subsistence
